CREATE DATABASE `BAITAP_VIEW_INDEX_STORE PROCEDURE`;

USE `BAITAP_VIEW_INDEX_STORE PROCEDURE`;
CREATE TABLE `PRODUCTS`(
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_CODE` VARCHAR(20),
    `PRODUCT_NAME` VARCHAR(50),
    `PRODUCT_PRICE` LONG DEFAULT (25000),
    `PRODUCT_AMOUNT` LONG DEFAULT (500),
    `PRODUC_DESCRIPTION` VARCHAR (1234) DEFAULT 'NOTHING',
    `PRODUC_STATUS` INT
);

INSERT INTO `PRODUCTS` (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_STATUS)
VALUES ('A1', 'PRODUCT1',1),
       ('A2','PRODUCT2',0),
       ('A3','PRODUCT3',1),
       ('A4','PRODUCT4',0),
       ('A5','PRODUCT5',1),
       ('A6','PRODUCT6',0),
       ('A7','PRODUCT7',1),
       ('A8','PRODUCT8',1),
       ('A9','PRODUCT9',1),
       ('A10','PRODUCT10',0),
       ('A11','PRODUCT11',0),
       ('A12','PRODUCT12',1),
       ('A13','PRODUCT13',0),
       ('A14','PRODUCT14',1),
       ('A145','PRODUCT15',0);

ALTER TABLE `PRODUCTS`
ADD UNIQUE INDEX `product_index` (PRODUCT_CODE);

CREATE VIEW `products_view` AS
    SELECT PRODUCT_CODE AS CODE, PRODUCT_NAME AS NAME, PRODUCT_PRICE AS PRICE, PRODUC_STATUS AS STATUS
FROM `PRODUCTS`;
SELECT * FROM products_view;

DROP TABLE PRODUCTS;

CREATE OR REPLACE VIEW `products_view` AS
    SELECT PRODUCT_CODE AS CODE, PRODUCT_NAME AS NAME, PRODUCT_PRICE AS PRICE
FROM `PRODUCTS`;

DELIMITER //
CREATE PROCEDURE `findProduct` (IN FINDID INT)
BEGIN
   SELECT * FROM `PRODUCTS`
       WHERE FINDID = ID;
END //
DELIMITER ;

CALL findProduct(2);
